export function Footer() {
  return (
    <div className="bg-gray-50 px-8 py-6 border-t text-center text-gray-600">
      <p className="mb-2">📊 This report is generated by Dvara E-Registry</p>
      <p>
        <strong>Need help?</strong> Contact our agricultural extension officer or call our helpline: 1800-XXX-FARM
      </p>
    </div>
  );
}